/**
 * 389. Find the Difference
 * https://leetcode.com/problems/find-the-difference/description/
 * 
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
    //method 1
    let arr1 = new Array(26).fill(0);
    let arr2 = new Array(26).fill(0);
    for (let i = 0; i < s.length; i++) {
        let n = s[i].charCodeAt() - "a".charCodeAt();
        //console.log(n);
        arr1[n]++;
    }
    for (let i = 0; i < t.length; i++) {
        let n2 = t[i].charCodeAt() - "a".charCodeAt();
        arr2[n2]++;
    }
    for (let i = 0; i < 26; i++) {
        if (arr1[i] != arr2[i]) {
            let n = "a".charCodeAt() + i;
            return String.fromCharCode(n);
        }
    }

    //method 2,利用异或(xor):利用异或的性质，相同位返回0(数字自己和自己异或等于0)，这样相同的字符都抵消了，剩下的就是后加的那个字符
    let res = 0;
    for (let i = 0; i < s.length; i++) {
        res = res ^ s[i].charCodeAt();
    }
    for (let i = 0; i < t.length; i++) {
        res = res ^ t[i].charCodeAt();
    }
    return String.fromCharCode(res);
};